#!/bin/sh
#NotReady
java -cp youtube-playlist-fetcher.main.jar com.xymenapps.youtube.YPlaylist_Fetcher
youtube-dl -i --download-archive 'BESTVIDEO-BESTAUDIO-MP4-MP3/archive-mp4.txt' -k --no-post-overwrites --recode-video mp4 --audio-format mp3 -f bestvideo+bestaudio -o 'BESTVIDEO-BESTAUDIO-MP4-MP3/%(playlist_title)s/%(title)s.%(ext)s' -a test_playlists
rm -rf Music-Videos/MP4
mkdir Music-Videos
cp -rv BESTVIDEO-BESTAUDIO-MP4-MP3 Music-Videos/MP4
find Music-Videos/MP4 -type f -name *.txt -delete
find Music-Videos/MP4 -type f -name *.f*.mp4 -delete
find Music-Videos/MP4 -type f -name *.webm -delete
find Music-Videos/MP4 -type f -name *.opus -delete
find Music-Videos/MP4 -type f -name *.mkv -delete
find Music-Videos/MP4 -type f -name *.m4a -delete
find Music-Videos/MP4 -type f -name *.mp3 -delete
